"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[aliases]
bk = ["bookmark"]
bkc = ["bookmark", "create"]
bkm = ["bookmark", "move"]
bkmt = ["bookmark", "move", "--to"]
bkmtp = ["bookmark", "move", "--to", "@-"]
cim = ["commit", "--message"]
dc = ["describe"]
dcm = ["describe", "--message"]
dcp = ["describe", "@-"]
df = ["diff"]
dfp = ["diff", "--revisions", "@-"]
dfr = ["diff", "--revisions"]
ed = ["edit"]
gt = ["git"]
gtp = ["git", "push"]
lg = ["log"]
lga = ["log", "--revisions", "::"]
lgav = ["log", "--revisions", "::", "--template", "builtin_log_detailed"]
lgv = ["log", "--template", "builtin_log_detailed"]
rb = ["rebase"]
rbd = ["rebase", "--destination"]
sh = ["show"]
shp = ["show", "@-"]
sp = ["split"]
sq = ["squash"]
sqf = ["squash", "--from"]
ud = ["undo"]

[colors]
"timestamp ago" = { "fg" = "ansi-color-30", italic = true }

[git]
private-commits = "description(glob:'local:*') | description(glob:'private:*') | description(glob:'wip:*')"

[template-aliases]
'format_timestamp(ts)' = 'ts.ago() ++ " " ++ ts.local().format("%c")'

[ui]
default-command = "log"
diff-formatter = "difft"
merge-editor = "mergiraf"

[user]
name = "Morgan Courbet"
email = {{ .gitemail | quote }}

[working-copy]
{{ if eq .chezmoi.os "windows" -}}
eol-conversion = "input-output"
{{- end }}
